services:
  clarisse-llm-server:
    image: vllm/vllm-openai:latest
    container_name: clarisse-llm-server
    profiles: ["clarisse"]
    gpus: all
    environment:
      - TZ=Europe/Lisbon
      - VLLM_LOGGING_CONFIG_PATH=/app/clarisse-llm-logging.json
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./llama/custom_llama_tool_parser.py:/app/custom_llama_tool_parser.py
      - ./llama/tool_chat_template_llama3.1_json.jinja:/app/tool_chat_template_llama3.1_json.jinja
      - ./configs/logging/clarisse-llm-logging.json:/app/clarisse-llm-logging.json:ro
      - ./logs:/app/logs
    ports:
      - "8081:8000"
    shm_size: '64gb'
    restart: unless-stopped
    command: >
      --model neuralmagic-ent/Llama-3.3-70B-Instruct-quantized.w8a8
      --api-key token-abc123
      --enable-auto-tool-choice
      --tool-call-parser llama3_json
      --chat-template /app/tool_chat_template_llama3.1_json.jinja
      --max-model-len 16000
      --enable-prefix-caching
      --enable-chunked-prefill
      --max-num-batched-tokens 8192
      --gpu-memory-utilization 0.35
      --tensor-parallel-size 4
      --tool-parser-plugin /app/custom_llama_tool_parser.py

  clarisse-stt-server:
    build:
      context: .
      dockerfile: Dockerfile.stt
    image: vllm-openai-audio:0.11.0
    container_name: clarisse-stt-server
    profiles: ["clarisse"]
    gpus: all
    environment:
      - TZ=Europe/Lisbon
      - VLLM_LOGGING_CONFIG_PATH=/app/clarisse-stt-logging.json
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./configs/logging/clarisse-stt-logging.json:/app/clarisse-stt-logging.json:ro
      - ./logs:/app/logs
    ports:
      - "8082:8000"
    shm_size: '8gb'
    restart: unless-stopped
    command: >
      --model fsicoli/whisper-large-v3-pt-cv19-fleurs
      --tensor-parallel-size 4
      --gpu-memory-utilization 0.05

  clarisse-embed-server:
    image: vllm/vllm-openai:latest
    container_name: clarisse-embed-server
    profiles: ["clarisse"]
    gpus: all
    environment:
      - TZ=Europe/Lisbon
      - VLLM_LOGGING_CONFIG_PATH=/app/clarisse-embed-logging.json
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./configs/logging/clarisse-embed-logging.json:/app/clarisse-embed-logging.json:ro
      - ./logs:/app/logs
    ports:
      - "8083:8000"
    shm_size: '8gb'
    restart: unless-stopped
    command: >
      --model Qwen/Qwen3-Embedding-0.6B
      --gpu-memory-utilization 0.04
      --max-model-len 4096
      --tensor-parallel-size 4
      --task embed

  clarisse-image-server:
    image: vllm/vllm-openai:latest
    container_name: clarisse-image-server
    profiles: ["clarisse"]
    gpus: all
    environment:
      - TZ=Europe/Lisbon
      - VLLM_LOGGING_CONFIG_PATH=/app/clarisse-image-logging.json
      - VLLM_USE_FLASHINFER_MOE_FP16=1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./configs/logging/clarisse-image-logging.json:/app/clarisse-image-logging.json:ro
      - ./logs:/app/logs
    ports:
      - "8084:8000"
    shm_size: '32gb'
    restart: unless-stopped
    command: >
      --model Qwen/Qwen3-VL-30B-A3B-Instruct
      --api-key token-abc123
      --tensor-parallel-size 4
      --max-model-len 128000
      --mm-encoder-tp-mode data
      --mm-processor-cache-gb 0
      --enable-expert-parallel
      --limit-mm-per-prompt.video 0
      --async-scheduling
      --gpu-memory-utilization 0.15
      --chat-template-content-format openai
  

  ikea-image-server:
    image: vllm/vllm-openai:latest
    container_name: ikea-image-server
    profiles: ["ikea"]
    gpus: all
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8094:8000"
    shm_size: '64gb'
    restart: unless-stopped
    command: >
      --model Qwen/Qwen3-VL-235B-A22B-Thinking-FP8
      --api-key token-abc123
      --tensor-parallel-size 4
      --max-model-len 128000
      --reasoning-parser deepseek_r1
      --mm-encoder-tp-mode data
      --mm-processor-cache-gb 0
      --enable-expert-parallel
      --limit-mm-per-prompt.video 0
      --async-scheduling
      --gpu-memory-utilization 0.6
      --chat-template-content-format openai

  gpt-oss-server:
    image: vllm/vllm-openai:latest
    container_name: gpt-oss-server
    profiles: ["gpt"]
    gpus: all
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8085:8000"
    shm_size: '32gb'
    restart: unless-stopped
    command: >
      --model openai/gpt-oss-120b
      --api-key token-abc123
      --tensor-parallel-size 4
      --async-scheduling
      --gpu-memory-utilization 0.35

  lara-stt-server:
    build:
      context: .
      dockerfile: Dockerfile.stt
    image: vllm-openai-audio:0.11.0
    container_name: lara-stt-server
    profiles: ["lara"]
    gpus: all
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8092:8000"
    shm_size: '8gb'
    restart: unless-stopped
    command: >
      --model openai/whisper-large-v3
      --tensor_parallel_size=4
      --gpu-memory-utilization 0.1