services:
  llm-server:
    image: vllm/vllm-openai:latest
    container_name: llm-server
    profiles: ["clarisse"]
    gpus: all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./custom_llama_tool_parser.py:/app/custom_llama_tool_parser.py
      - ./tool_chat_template_llama3.1_json.jinja:/app/tool_chat_template_llama3.1_json.jinja
    ports:
      - "8081:8000"
    shm_size: '64gb'
    restart: unless-stopped
    command: >
      --model neuralmagic-ent/Llama-3.3-70B-Instruct-quantized.w8a8
      --api-key token-abc123
      --enable-auto-tool-choice
      --tool-call-parser llama3_json
      --chat-template /app/tool_chat_template_llama3.1_json.jinja
      --max-model-len 16000
      --enable-prefix-caching
      --enable-chunked-prefill
      --max-num-batched-tokens 8192
      --gpu-memory-utilization 0.7
      --tensor-parallel-size 4
      --tool-parser-plugin /app/custom_llama_tool_parser.py

  stt-server:
    build:
      context: .
      dockerfile: Dockerfile.stt
    image: vllm-openai-audio:0.11.0
    container_name: stt-server
    profiles: ["clarisse"]
    gpus: all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8082:8000"
    shm_size: '8gb'
    restart: unless-stopped
    command: >
      --model fsicoli/whisper-large-v3-pt-cv19-fleurs
      --tensor-parallel-size 4
      --gpu-memory-utilization 0.1

  embed-server:
    image: vllm/vllm-openai:latest
    container_name: embed-server
    profiles: ["clarisse"]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8083:8000"
    shm_size: '8gb'
    restart: unless-stopped
    gpus: all
    command: >
      --model Qwen/Qwen3-Embedding-0.6B
      --gpu-memory-utilization 0.04
      --max-model-len 4096
      --tensor-parallel-size 4
      --task embed
  

  qwen-vl-server:
    image: vllm/vllm-openai:latest
    container_name: qwen-vl-server
    profiles: ["qwen-vl"]
    gpus: all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8084:8000"
    shm_size: '64gb'
    restart: unless-stopped
    command: >
      --model Qwen/Qwen3-VL-235B-A22B-Thinking-FP8
      --api-key token-abc123
      --tensor-parallel-size 4
      --max-model-len 128000
      --reasoning-parser deepseek_r1
      --mm-encoder-tp-mode data
      --mm-processor-cache-gb 0
      --enable-expert-parallel
      --limit-mm-per-prompt.video 0
      --async-scheduling
      --gpu-memory-utilization 0.95
      --chat-template-content-format openai
